### ISSUE TITLE
Pre-Trained Models for the other styles

### ISSUE THREAD

**Issue by nelaturuharsha** [AlonShoshan10/dynamic_net#3]
Thank you so much for the fantastic work.

-> I was wondering if the pre-trained models for the other styles would be provided as well and the same for the dual network?
-> The trained_models I believe has only one style available, or is there something I'm missing?

Thank you!

**Comment by AlonShoshan10** [comment]
Hi, there is a link to all the pre-trained networks in the dynamic_style_transfer setup instructions (link: https://drive.google.com/drive/folders/1zdxj94Y9754-dSxYKdSBe7BzzNmtenlr?usp=sharing). All the models should be in the "trained_nets.rar" file. There are also instructions on where to extract the networks.

thanks:)

**Comment by nelaturuharsha** [comment]
Thank you so much, I believe I downloaded an alternate version of trained_nets.rar and hence was confused. Thank you so much for sharing your work once again and the prompt response.
